fix quorum scripts

diff --git a/docker/docker-compose-anonify-quorum.yml b/docker/docker-compose-anonify-quorum.yml
--- a/docker/docker-compose-anonify-quorum.yml
+++ b/docker/docker-compose-anonify-quorum.yml
@@ -18,7 +18,52 @@ x-quorum-def:
   entrypoint:
     - /bin/sh
     - -c
-    - ./scripts/quorum-node.sh
+    - |
+      UDS_WAIT=10
+      for i in $$(seq 1 100)
+      do
+        set -e
+        if [ -S $${PRIVATE_CONFIG} ] && \
+          [ "I'm up!" == "$$(wget --timeout $${UDS_WAIT} -qO- --proxy off 172.16.239.10$${NODE_ID}:9000/upcheck)" ];
+        then break
+        else
+          echo "Sleep $${UDS_WAIT} seconds. Waiting for TxManager."
+          sleep $${UDS_WAIT}
+        fi
+      done
+      DDIR=/qdata/dd
+      rm -rf $${DDIR}
+      mkdir -p $${DDIR}/keystore
+      mkdir -p $${DDIR}/geth
+      cp /examples/raft/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
+      cp /examples/keys/key$${NODE_ID} $${DDIR}/keystore/
+      cat /examples/permissioned-nodes.json | sed 's/^\(.*\)@.*\?\(.*\)raftport=5040\([0-9]\)\(.*\)$$/\1@172.16.239.1\3:21000?discport=0\&raftport=50400\4/g' > $${DDIR}/static-nodes.json
+      cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
+      cat $${DDIR}/static-nodes.json
+      GENESIS_FILE="/examples/istanbul-genesis.json"
+      if [ "${QUORUM_CONSENSUS:-istanbul}" == "raft" ]; then
+        GENESIS_FILE="/examples/genesis.json"
+      fi
+      NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
+      GETH_ARGS_raft="--raft --raftport 50400"
+      GETH_ARGS_istanbul="--emitcheckpoints --istanbul.blockperiod 1 --mine --minerthreads 1 --syncmode full"
+      geth --datadir $${DDIR} init $${GENESIS_FILE}
+      geth \
+        --identity node$${NODE_ID}-${QUORUM_CONSENSUS:-istanbul} \
+        --datadir $${DDIR} \
+        --permissioned \
+        --nodiscover \
+        --verbosity 5 \
+        --networkid $${NETWORK_ID} \
+        --rpc \
+        --rpcvhosts=* \
+        --rpcaddr 0.0.0.0 \
+        --rpcport 8545 \
+        --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,${QUORUM_CONSENSUS:-istanbul} \
+        --port 21000 \
+        --unlock 0 \
+        --password /examples/passwords.txt \
+        ${QUORUM_GETH_ARGS:-} $${GETH_ARGS_${QUORUM_CONSENSUS:-istanbul}}
 
 x-tx-manager-def:
   &tx-manager-def
@@ -36,7 +81,109 @@ x-tx-manager-def:
   entrypoint:
     - /bin/sh
     - -c
-    - ./scripts/quorum-tx-manager.sh
+    - |
+      DDIR=/qdata/tm
+      rm -rf $${DDIR}
+      mkdir -p $${DDIR}
+      DOCKER_IMAGE="${QUORUM_TX_MANAGER_DOCKER_IMAGE:-quorumengineering/tessera:0.10.0}"
+      TX_MANAGER=$$(echo $${DOCKER_IMAGE} | sed 's/^.*\/\(.*\):.*$$/\1/g')
+      echo "TxManager: $${TX_MANAGER}"
+      case $${TX_MANAGER}
+      in
+        tessera)
+          cp /examples/keys/tm$${NODE_ID}.pub $${DDIR}/tm.pub
+          cp /examples/keys/tm$${NODE_ID}.key $${DDIR}/tm.key
+          #extract the tessera version from the jar
+          TESSERA_VERSION=$$(unzip -p /tessera/tessera-app.jar META-INF/MANIFEST.MF | grep Tessera-Version | cut -d" " -f2)
+          echo "Tessera version (extracted from manifest file): $${TESSERA_VERSION}"
+          # sorting versions to target correct configuration
+          V08=$$(echo -e "0.8\n$${TESSERA_VERSION}" | sort -n -r -t '.' -k 1,1 -k 2,2 | head -n1)
+          V09AndAbove=$$(echo -e "0.9\n$${TESSERA_VERSION}" | sort -n -r -t '.' -k 1,1 -k 2,2 | head -n1)
+          TESSERA_CONFIG_TYPE="-09"
+          case "$${TESSERA_VERSION}" in
+              "$${V09AndAbove}")
+                  TESSERA_CONFIG_TYPE="-09"
+                  ;;
+          esac
+
+          echo Config type $${TESSERA_CONFIG_TYPE}
+
+          #generating the two config flavors
+          cat <<EOF > $${DDIR}/tessera-config-09.json
+          {
+            "useWhiteList": false,
+            "jdbc": {
+              "username": "sa",
+              "password": "",
+              "url": "jdbc:h2:./$${DDIR}/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
+              "autoCreateTables": true
+            },
+            "serverConfigs":[
+            {
+              "app":"ThirdParty",
+              "enabled": true,
+              "serverAddress": "http://$$(hostname -i):9080",
+              "communicationType" : "REST"
+            },
+            {
+              "app":"Q2T",
+              "enabled": true,
+              "serverAddress": "unix:$${DDIR}/tm.ipc",
+              "communicationType" : "REST"
+            },
+            {
+              "app":"P2P",
+              "enabled": true,
+              "serverAddress": "http://$$(hostname -i):9000",
+              "sslConfig": {
+                "tls": "OFF"
+              },
+              "communicationType" : "REST"
+            }
+            ],
+            "peer": [
+               {
+                   "url": "http://txmanager1:9000"
+               },
+               {
+                   "url": "http://txmanager2:9000"
+               },
+               {
+                   "url": "http://txmanager3:9000"
+               }
+            ],
+            "keys": {
+              "passwords": [],
+              "keyData": [
+                {
+                  "config": $$(cat $${DDIR}/tm.key),
+                  "publicKey": "$$(cat $${DDIR}/tm.pub)"
+                }
+              ]
+            },
+            "alwaysSendTo": []
+          }
+      EOF
+          cat $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
+          java -Xms128M -Xmx128M -jar /tessera/tessera-app.jar -configfile $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
+          ;;
+        constellation)
+          echo "socket=\"$${DDIR}/tm.ipc\"\npublickeys=[\"/examples/keys/tm$${NODE_ID}.pub\"]\n" > $${DDIR}/tm.conf
+          constellation-node \
+            --url=http://$$(hostname -i):9000/ \
+            --port=9000 \
+            --socket=$${DDIR}/tm.ipc \
+            --othernodes=http://172.16.239.101:9000/,http://172.16.239.102:9000/,http://172.16.239.103:9000/,http://172.16.239.104:9000/,http://172.16.239.105:9000/ \
+            --publickeys=/examples/keys/tm$${NODE_ID}.pub \
+            --privatekeys=/examples/keys/tm$${NODE_ID}.key \
+            --storage=$${DDIR} \
+            --verbosity=4
+          ;;
+        *)
+          echo "Invalid Transaction Manager"
+          exit 1
+          ;;
+      esac
 
 services:
   sgx_machine1:
@@ -140,7 +287,7 @@ services:
     << : *quorum-def
     hostname: quorum_node2
     ports:
-      - "22000:8545"
+      - "22001:8545"
     volumes:
       - vol1:/qdata
       - ./.quorum:/examples:ro
@@ -157,7 +304,7 @@ services:
     << : *tx-manager-def
     hostname: txmanager2
     ports:
-      - "9081:9080"
+      - "9082:9080"
     volumes:
       - vol1:/qdata
       - ./.quorum:/examples:ro
@@ -171,7 +318,7 @@ services:
     << : *quorum-def
     hostname: quorum_node3
     ports:
-      - "22000:8545"
+      - "22002:8545"
     volumes:
       - vol1:/qdata
       - ./.quorum:/examples:ro
@@ -188,7 +335,7 @@ services:
     << : *tx-manager-def
     hostname: txmanager3
     ports:
-      - "9081:9080"
+      - "9083:9080"
     volumes:
       - vol1:/qdata
       - ./.quorum:/examples:ro
